\connect project1sgd;

ALTER TABLE PARTSUPP
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);
ALTER TABLE PARTSUPP
ADD FOREIGN KEY (PS_SUPPKEY) references SUPPLIER (S_SUPPKEY),
ADD FOREIGN KEY (PS_PARTKEY) references PART (P_PARTKEY);
