USE Project1SGD;

/* ADD KEYS */
ALTER TABLE REGION
ADD PRIMARY KEY (R_REGIONKEY);

ALTER TABLE NATION
ADD PRIMARY KEY (N_NATIONKEY),
ADD KEY (N_REGIONKEY);
ALTER TABLE NATION
ADD FOREIGN KEY NATION_FK1 (N_REGIONKEY) references REGION (R_REGIONKEY);

ALTER TABLE CUSTOMER
ADD PRIMARY KEY (C_CUSTKEY),
ADD KEY (C_NATIONKEY);
ALTER TABLE CUSTOMER
ADD FOREIGN KEY CUSTOMER_FK1 (C_NATIONKEY) references NATION (N_NATIONKEY);

ALTER TABLE SUPPLIER
ADD PRIMARY KEY (S_SUPPKEY),
ADD KEY (S_NATIONKEY);
ALTER TABLE SUPPLIER
ADD FOREIGN KEY SUPPLIER_FK1 (S_NATIONKEY) references NATION (N_NATIONKEY);

ALTER TABLE PART
ADD PRIMARY KEY (P_PARTKEY);

ALTER TABLE PARTSUPP
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY),
ADD KEY (PS_PARTKEY),
ADD KEY (PS_SUPPKEY);
ALTER TABLE PARTSUPP
ADD FOREIGN KEY PARTSUPP_FK1 (PS_SUPPKEY) references SUPPLIER (S_SUPPKEY),
ADD FOREIGN KEY PARTSUPP_FK2 (PS_PARTKEY) references PART (P_PARTKEY);

ALTER TABLE ORDERS
ADD PRIMARY KEY (O_ORDERKEY),
ADD KEY (O_CUSTKEY);
ALTER TABLE ORDERS
ADD FOREIGN KEY ORDERS_FK1 (O_CUSTKEY) references CUSTOMER (C_CUSTKEY);

ALTER TABLE LINEITEM
ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER),
ADD KEY (L_ORDERKEY),
ADD KEY (L_PARTKEY,L_SUPPKEY);
ALTER TABLE LINEITEM
ADD FOREIGN KEY LINEITEM_FK1 (L_ORDERKEY)  references ORDERS (O_ORDERKEY),
ADD FOREIGN KEY LINEITEM_FK2 (L_PARTKEY,L_SUPPKEY) references PARTSUPP (PS_PARTKEY,PS_SUPPKEY);

